name: Execute SQL Queries

on:
  push:
    branches:
      - main

jobs:
  query:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install pymysql --target=myenv/lib/python3.12/site-packages/

      - name: Set PYTHONPATH
        run: |
          echo "export PYTHONPATH=\$PYTHONPATH:$(pwd)/myenv/lib/python3.12/site-packages" >> $GITHUB_ENV

      - name: Clone or update repository
        run: |
          mkdir -p /home/radmin/rfam
          cd /home/radmin/rfam
          if [ -d "cirfam" ]; then
            cd cirfam && git pull
          else
            git clone https://github.com/Honorwizz/cirfam.git
          fi

      - name: Run SQL script
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          python /home/radmin/rfam/cirfam/script.py
